using CarsApp.Domain.Entities;

namespace CarsApp.Domain.Lab7.TemplateMethod;

public abstract class ServiceReportTemplate
{
    public abstract string ReportType { get; }

    public ServiceReportDocument Generate(ServiceOrder order)
    {
        ValidateOrder(order);

        var sections = new List<string>
        {
            BuildTitle(order),
            BuildVehicleSection(order),
            BuildServiceDetailsSection(order)
        };

        var recommendationSection = BuildRecommendationSection(order);
        if (!string.IsNullOrWhiteSpace(recommendationSection))
        {
            sections.Add(recommendationSection);
        }

        sections.Add(BuildCostSection(order));
        sections.Add(BuildFooter(order));

        return new ServiceReportDocument(ReportType, sections);
    }

    protected virtual void ValidateOrder(ServiceOrder order)
    {
        if (order == null)
        {
            throw new ArgumentNullException(nameof(order));
        }

        if (order.Vehicle == null)
        {
            throw new InvalidOperationException("A service report requires a vehicle.");
        }

        if (order.Services.Count == 0)
        {
            throw new InvalidOperationException("A service report requires at least one service.");
        }
    }

    protected virtual string BuildTitle(ServiceOrder order)
    {
        return $"{ReportType} | Order {order.OrderId}";
    }

    protected virtual string BuildVehicleSection(ServiceOrder order)
    {
        var vehicle = order.Vehicle;
        return $"Vehicle: {vehicle.GetVehicleType()} {vehicle.Make} {vehicle.Model} {vehicle.Year}";
    }

    protected abstract string BuildServiceDetailsSection(ServiceOrder order);

    protected abstract string BuildCostSection(ServiceOrder order);

    protected virtual string? BuildRecommendationSection(ServiceOrder order)
    {
        return null;
    }

    protected virtual string BuildFooter(ServiceOrder order)
    {
        return "Generated by CarsApp service reporting workflow.";
    }
}
